### ISSUE TITLE
require-pragma support

### ISSUE THREAD

**Issue by websirnik** [prettier/prettier-eslint-cli#112]
- `prettier-eslint-cli` version: v4.4.0
- `prettier` version: 1.7.4

I'm using `prettier-eslint-cli` with https://github.com/jonlabelle/SublimeJsPrettier, and it sets `--require-pragma` flag. As the result, the cli throws `Unknown argument: require-pragma` exception. `require-pragma` introduced prettier 1.7

**Comment by kentcdodds** [comment]
Hi @websirnik!

That seems odd to me. I didn't think that our CLI cared about arguments that it doesn't know about.

Feel free to dig in and [make a PR](http://makeapullrequest.com/) :smile:

**Comment by zaygraveyard** [comment]
I'm having the same problem as @websirnik.
@kentcdodds I think it's because of the call to [`strict()`](https://github.com/yargs/yargs/blob/master/docs/api.md#strictenabledtrue) in [parse.js:161](https://github.com/prettier/prettier-eslint-cli/blob/master/src/parser.js#L161) (I haven't tested yet).

I'd make a PR but I don't know which is better, removing the `strict()` call or adding `--require-pragma` option and any other option that might be missing?

**Comment by zaygraveyard** [comment]
Just tested removing the `strict()` call and it does indeed fix the problem.

**Comment by zimme** [comment]
Supported since `4.7.0`.
