### ISSUE TITLE
Is always attempting to format node_modules

### ISSUE THREAD

**Issue by DontPanic345** [prettier/prettier-eslint-cli#39]
even when I try explicitly ignoring the folder

```
scripts: {
    "format": "prettier-eslint \"./**/*.js\" --ignore \"./node_modules/**\" --write"
}
```

**Comment by kentcdodds** [comment]
Hmmm... That's weird. Does it not work if you exclude the `--ignore`? As you see [here](https://github.com/prettier/prettier-eslint-cli/blob/master/src/format-files.js#L157) so long as you're not explicitly trying to format `node_modules`, it will be ignored.

Could you dig a little deeper?

**Comment by DontPanic345** [comment]
Not sure how it was happening but whenever I use `\"./**/*.js\"` it will always include the node_modules folder.

I just explicitly included all the folders I wanted to format.

**Comment by kentcdodds** [comment]
Ok, feel free to dig deeper to see if there really is a bug.

**Comment by dlindahl** [comment]
I am also running into this issue. An initial poke at the source code seems to indicate that `prettier-eslint-cli` is honoring the `.eslintignore` file that is shipped with installed NPM modules. I added some `console.info`s inside `isFilePathMatchedByEslintignore`, just before the `return`, and here is a snippet of the output:

```
eslintignorePath /Users/dlindahl/Work/website/.eslintignore
eslintignoreDir /Users/dlindahl/Work/website
isIgnored? node_modules/fsevents/node_modules/punycode/punycode.js true
---
eslintignorePath /Users/dlindahl/Work/website/node_modules/fsevents/node_modules/qs/.eslintignore
eslintignoreDir /Users/dlindahl/Work/website/node_modules/fsevents/node_modules/qs
isIgnored? dist/qs.js true
---
eslintignorePath /Users/dlindahl/Work/website/node_modules/fsevents/node_modules/qs/.eslintignore
eslintignoreDir /Users/dlindahl/Work/website/node_modules/fsevents/node_modules/qs
isIgnored? lib/formats.js false
```

You can see when the parser is looping through `punycode`, it is using the project `.eslintignore`. But when its looping throug `fsevents`, it picks up the `.eslintignore` file contained in the `fsevents` module which is configured only to ignore its own `dist` directory.

Because `fsevents` isn't ignoring `node_modules` on its own, `prettier-eslint-cli` starts to process all of the dependencies of `fsevents`.

I want to say that the way `prettier-eslint-cli` treats nested `.eslintignore` paths seems like a bug to me. I would think that the project settings should trump anything nested within it. Is this the expected behavior?

**Comment by kentcdodds** [comment]
This is definitely not expected behavior. Due to [this](https://github.com/prettier/prettier-eslint-cli/blob/master/src/format-files.js#L156-L162) (specifically `globOptions.ignore`), those files should never be included in the array of files that are processed. If you could figure out why those are included, that would be helpful.

**Comment by dlindahl** [comment]
I have to imagine its due to [`getNearestEslintignorePath(filePath)`](https://github.com/prettier/prettier-eslint-cli/blob/8567216b564ecb395d6203b04a8491a6d61e410b/src/format-files.js#L203-L206)

Based on the name of the function, it would make sense that, given a path deep inside `node_modules`, that it would _find the nearest `.eslintlignore`_ and use it. I would imagine that the intention of `getNearestEslintignorePath` is to find an `.eslintignore` file in the root of the project _or above_ (not below).

At first thought, a good place to start would be to restrict this method from going down into project sub-paths. However, in something like a [lerna](https://lernajs.io) repo, I supposed it would be possible to have many `.eslintignore` files in a single project. So on second thought, `getNearestEslintignorePath` should itself be prevented from ever looking into `node_modules`... maybe?

**Comment by kentcdodds** [comment]
Thanks for chipping in @dlindahl. The fact is that due to the code I linked to before, those file paths should never even reach `getNearestEslintignorePath`. They shouldn't be included in the `map` called on `rxGlob` because they should be ignored via `globOptions`. So what we need to figure out is why those files are being matched by the glob. A good place to start would be to add a `console.log({fileGlob, globOptions})` above [this line](https://github.com/prettier/prettier-eslint-cli/blob/8567216b564ecb395d6203b04a8491a6d61e410b/src/format-files.js#L162)

**Comment by dlindahl** [comment]
The output of `getFilesFromGlob` is:

```js
{ fileGlob: './**/*.js',
  globOptions: { ignore: [ '**/node_modules/**' ] } }
```

**Comment by kentcdodds** [comment]
Ok, so based on that we shouldn't be seeing anything from node_modules included. Can anyone investigate why we are?

**Comment by denis-sokolov** [comment]
@kentcdodds, perhaps you want to reopen this issue?

**Comment by kentcdodds** [comment]
It's unclear this is an issue with the package. Feel free to investigate further.
