### ISSUE TITLE
eslint disable moves to next line

### ISSUE THREAD

**Issue by ritz078** [prettier/prettier-eslint-cli#48]
```js
if (!global.__DEV__) { // eslint-disable-line
}
```
changes to 

```js
if (!global.__DEV__) {
  // eslint-disable-line
}
```

and hence shows error in eslint.

**Comment by kentcdodds** [comment]
Hi @ritz078, thanks for the report.

This is due to how prettier reformats inline comments. The solution is:

```js
 // eslint-disable-next-line
if (!global.__DEV__) {
}
```

Would you be interested in adding a note about this in the README of [`prettier-eslint`](https://github.com/prettier/prettier-eslint)?

In either case, this is not possible for us to do anything about. Good luck!

**Comment by ritz078** [comment]
Will open a PR soon. Thanks.
