### ISSUE TITLE
Version 4.x stopped inferring options from ESLint config

### ISSUE THREAD

**Issue by mrm007** [prettier/prettier-eslint-cli#62]
- `prettier-eslint-cli` version: 4.0.1
- `prettier` version: 1.3.1
- `eslint` version: 3.19.0

Relevant code/config.
See [example repo](mrm007/prettier-eslint-cli_bug). Run with `yarn start`. There is a `v3` branch for `prettier-eslint-config@3`.

What you did:

With `prettier-eslint-config@4` the inferred options are:

```javascript
  "prettierOptions": {
    "bracketSpacing": true,
    "parser": "babylon",
    "printWidth": 80,
    "semi": true,
    "singleQuote": false,
    "tabWidth": 2,
    "trailingComma": "none",
    "useTabs": false,
  },
```

The expected options are the ones obtained with `prettier-eslint-config@3`:

```javascript
  "prettierOptions": {
    "bracketSpacing": true,
    "parser": "babylon",
    "printWidth": 120,
    "semi": true,
    "singleQuote": true,
    "tabWidth": 2,
    "trailingComma": "all",
    "useTabs": false,
  },
```

Problem description:

The new behaviour is caused by the changes in #59, specifically [this change][sec]. Default options specified for yargs take precedence so the ESLint config getters never get called:

![code](https://photos-5.dropbox.com/t/2/AAAPuLNcaKCVW48H8djJLGnyCs6X1ZS1kb-0qL0htzNdAQ/12/1275359/png/32x32/3/1495742400/0/2/Screenshot%202017-05-26%2000.58.10.png/ENaQiwEYzqHyyAEgAigC/m3F2EvcUiZJMRD-ARsnJ-_mGlwckcfS-UiYKGje-kkQ?dl=0&size=32x32&size_mode=5)

[sec]: https://github.com/prettier/prettier-eslint-cli/pull/59/files#diff-6947033678b93d106e25614dd972e66fR80

**Comment by kentcdodds** [comment]
Ah! Yeah, that's a problem! Glad that I pushed that as a major version bump so it didn't mess everyone up unsuspectingly!

So I think that the problem is that the default values from the CLI should be used as [`fallbackPrettierOptions`](https://github.com/prettier/prettier-eslint#fallbackprettieroptions-object) and right now they're being used as `prettierOptions` which overrides the prettier options.

So I'm pretty sure the solution would be to remove the `default` values for all the prettier options. `prettier-eslint` has the defaults already so there's really no need to have them at all.

Would you like to [make a pull request](http://makeapullrequest.com) to do that?

**Comment by mrm007** [comment]
Will do! I wasn't sure how to handle it but now that you gave me the answer, I can.
